[NewRepo]
  newRepoClone = false
  newRepoDataFile = false
  newRepoUrl = ""

[Init]

[Add]
  addName = ""
  addEntry = ""
  addExisting = false
  addFormat = false

[Read]

[Sync]
  syncMessage = "New changes"
  syncAuth = true
  syncPush = false

[Link]

[Edit]
  editName = ""
  editEditor = ""
  editFormat = true

[Config]
  configNew = false
  configRead = true
