[NewRepo]
  newRepoClone = false
  newRepoDataFile = false
  newRepoUrl = ""

[Add]
  addName = ""
  addEntry = ""
  addExisting = false
  addFormat = false

[Sync]
  syncMessage = "New changes"
  syncAuth = true
  syncPush = false

[Edit]
  editName = ""
  editEditor = ""
  editFormat = true

[Config]
  configNew = false
  configRead = true
