format = """
[░▒▓](#a3aed2)\
$directory\
[](bg:#769ff0 fg:#a3aed2)\
$git_branch\
$git_status\
[](fg:#769ff0)\
\n$character
"""

right_format = """
$status\
$cmd_duration
"""

[directory]
style = "bg:#a3aed2 fg:#090c0c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "Documents 󰈙"
"Downloads" = "Downloads "
"Music" = "Music  "
"Pictures" = "Pictures "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](#e3e5e5 bg:#769ff0)]($style)'

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
untracked = '?${count}'
modified = '!${count}'
format = '[[$untracked $ahead_behind $modified](#e3e5e5 bg:#769ff0)]($syle)'

[cmd_duration]
min_time = 1000
style = "bg:#1d2230"
format = 'took [$duration]($style) '

[status]
style = '#e3e5e5 bg:#769ff0'
success_symbol = ''
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false
